# Generated by Django 5.2.6 on 2025-09-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_cooking_time_alter_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='method',
        ),
    ]
