# Generated by Django 5.2.6 on 2025-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_description_recipe_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(max_length=30),
        ),
    ]
