# Generated by Django 5.2.6 on 2025-10-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(help_text='Describe the cooking method of the recipe'),
        ),
    ]
