# Generated by Django 5.2.6 on 2025-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_recipe_likes_recipe_liked_by_alter_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-10-17 10:00:00'),
            preserve_default=False,
        ),
    ]
