# Generated by Django 5.2.6 on 2025-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True, help_text='Describe the cooking method of the recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, default='no_picture.jpg', upload_to='recipes'),
        ),
    ]
